title:              Data Verse
email:              ajitosh.anand@gmail.com
description:        Data Science, Verse, Such stuff as dreams are made on
author:             Data Verse
baseurl:            ""
url:                "https://Ajitosh.github.io"

# Social Profiles
twitter_username:   "@tweetsofanand"
github_username:    "https://github.com/Ajitosh"
facebook_username:  
instagram_username:  
linkedin_username:  "https://www.linkedin.com/in/ajitosh/"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
